abstract: Apache module to authentificate trough a CAS server
author: Yves Agostini
build_requires: 
  Apache::src: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Apache-AuthCASSimple
no_index: 
  directory: 
    - inc
    - t
requires: 
  Apache::Constants: 0
  Apache::Log: 0
  Apache::ModuleConfig: 0
  Apache::Session::Wrapper: 0
  Authen::CAS::Client: 0
  DynaLoader: 0
tests: t/*.t
version: 0.0.1
